
GET http://localhost:3000/products/

###

GET http://localhost:3000/products/4

###

POST http://localhost:3000/products/
Content-Type: application/JSON

{
    "name": "In stock product with long name and description",
    "description": "This is a longer description of a product that is in stock and can be purchased right now.", 
    "price": "10.00",
    "stock": 8
}

###

PUT http://localhost:3000/products/4
Content-Type: application/JSON

{
    "name": "A old boot that is in stock",
    "description": "Why not buy it?",
    "price": "999.99",
    "stock": 10
}

###

DELETE http://localhost:3000/products/4
Content-Type: application/JSON


###

PATCH  http://localhost:3000/products/

