
GET http://localhost:3000/products/

###

GET http://localhost:3000/products/1

###

POST http://localhost:3000/
Content-Type: application/JSON

{
    "name": "Sample Product",
    "description": "This is a sample product",
    "price": "10.00",
    "stock": 10
}

###

PUT http://localhost:3000/
Content-Type: application/JSON

{
    "id": 1,
    "name": "Fresh Chicken",
    "description": "Fresh Chicken",
    "price": "999.99",
    "stock": 10
}

###

DELETE http://localhost:3000/
Content-Type: application/JSON

{
    "id": 2
}